export const LOGIN_RESULT = 'LOGIN_RESULT';
export const SET_USERSTATE = 'SET_USERSTATE';

export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_ANSWER = 'SAVE_ANSWER';

export const SET_SUBMITSTATE = 'SET_SUBMITSTATE';
